name: Running Tests

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: C-CaZG1B0-d6DYgemvzotJloAhrB_6XO
          POSTGRES_USER: ytxwgzxo
          POSTGRES_DB: ytxwgzxo

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # run steps required in the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm install


        env:
          URL: "postgres://ytxwgzxo:C-CaZG1B0-d6DYgemvzotJloAhrB_6XO@isabelle.db.elephantsql.com/ytxwgzxo"

      - name: Run the mock tests function
        run: npm test
        env:
          URL: postgres://ytxwgzxo:C-CaZG1B0-d6DYgemvzotJloAhrB_6XO@isabelle.db.elephantsql.com/ytxwgzxo
